import tkinter as tk
from tkinter import * 

root = tk.Tk()
root.geometry("800x400")
root.title("Compare Ages")

w = Label(root, text="Welcome to my first app, Compare Ages. Let's compare the ages of up to ten people at any given year.")
w.grid(row = 0, columnspan = 7)

line = Label(root, text="--<<-->>--<<-->>--<<-->>--<<-->>--<<-->>----<<-->>--<<-->>--<<-->>--<<-->>--<<-->>--<<--")
line.grid(row = 1, columnspan = 7)

ty_label = Label(root, text="Target Year:")
ty_label.grid(row = 3, column = 0, sticky = E, pady = 2)
ty_entry = Entry(root)
ty_entry.grid(row = 3, column = 1, pady = 2)

p1_label = Label(root, text="Person Name:")
p1_label.grid(row = 4, column = 0, sticky = E, pady = 2)
p1_entry = Entry(root)
p1_entry.grid(row = 4, column = 1, pady = 2)
p1yob_label = Label(root, text="Person YOB:")
p1yob_label.grid(row = 4, column = 2, sticky = E, pady = 2)
p1yob_entry = Entry(root)
p1yob_entry.grid(row = 4, column = 3, pady = 2) 

p2_label = Label(root, text="Person Name:")
p2_label.grid(row = 5, column = 0, sticky = E, pady = 2)
p2_entry = Entry(root)
p2_entry.grid(row = 5, column = 1, pady = 2)
p2yob_label = Label(root, text="Person YOB:")
p2yob_label.grid(row = 5, column = 2, sticky = E, pady = 2)
p2yob_entry = Entry(root)
p2yob_entry.grid(row = 5, column = 3, pady = 2) 

p3_label = Label(root, text="Person Name:")
p3_label.grid(row = 6, column = 0, sticky = E, pady = 2)
p3_entry = Entry(root)
p3_entry.grid(row = 6, column = 1, pady = 2)
p3yob_label = Label(root, text="Person YOB:")
p3yob_label.grid(row = 6, column = 2, sticky = E, pady = 2)
p3yob_entry = Entry(root)
p3yob_entry.grid(row = 6, column = 3, pady = 2) 

p4_label = Label(root, text="Person Name:")
p4_label.grid(row = 7, column = 0, sticky = E, pady = 2)
p4_entry = Entry(root)
p4_entry.grid(row = 7, column = 1, pady = 2)
p4yob_label = Label(root, text="Person YOB:")
p4yob_label.grid(row = 7, column = 2, sticky = E, pady = 2)
p4yob_entry = Entry(root)
p4yob_entry.grid(row = 7, column = 3, pady = 2) 

p5_label = Label(root, text="Person Name:")
p5_label.grid(row = 8, column = 0, sticky = E, pady = 2)
p5_entry = Entry(root)
p5_entry.grid(row = 8, column = 1, pady = 2)
p5yob_label = Label(root, text="Person YOB:")
p5yob_label.grid(row = 8, column = 2, sticky = E, pady = 2)
p5yob_entry = Entry(root)
p5yob_entry.grid(row = 8, column = 3, pady = 2)

p6_label = Label(root, text="Person Name:")
p6_label.grid(row = 9, column = 0, sticky = E, pady = 2)
p6_entry = Entry(root)
p6_entry.grid(row = 9, column = 1, pady = 2)
p6yob_label = Label(root, text="Person YOB:")
p6yob_label.grid(row = 9, column = 2, sticky = E, pady = 2)
p6yob_entry = Entry(root)
p6yob_entry.grid(row = 9, column = 3, pady = 2) 

p7_label = Label(root, text="Person Name:")
p7_label.grid(row = 10, column = 0, sticky = E, pady = 2)
p7_entry = Entry(root)
p7_entry.grid(row = 10, column = 1, pady = 2)
p7yob_label = Label(root, text="Person YOB:")
p7yob_label.grid(row = 10, column = 2, sticky = E, pady = 2)
p7yob_entry = Entry(root)
p7yob_entry.grid(row = 10, column = 3, pady = 2) 

p8_label = Label(root, text="Person Name:")
p8_label.grid(row = 11, column = 0, sticky = E, pady = 2)
p8_entry = Entry(root)
p8_entry.grid(row = 11, column = 1, pady = 2)
p8yob_label = Label(root, text="Person YOB:")
p8yob_label.grid(row = 11, column = 2, sticky = E, pady = 2)
p8yob_entry = Entry(root)
p8yob_entry.grid(row = 11, column = 3, pady = 2) 

p9_label = Label(root, text="Person Name:")
p9_label.grid(row = 12, column = 0, sticky = E, pady = 2)
p9_entry = Entry(root)
p9_entry.grid(row = 12, column = 1, pady = 2)
p9yob_label = Label(root, text="Person YOB:")
p9yob_label.grid(row = 12, column = 2, sticky = E, pady = 2)
p9yob_entry = Entry(root)
p9yob_entry.grid(row = 12, column = 3, pady = 2) 

p10_label = Label(root, text="Person Name:")
p10_label.grid(row = 13, column = 0, sticky = E, pady = 2)
p10_entry = Entry(root)
p10_entry.grid(row = 13, column = 1, pady = 2)
p10yob_label = Label(root, text="Person YOB:")
p10yob_label.grid(row = 13, column = 2, sticky = E, pady = 2)
p10yob_entry = Entry(root)
p10yob_entry.grid(row = 13, column = 3, pady = 2) 
 
def calc_ages():
  ty_get = ty_entry.get()
  ty_get = int(ty_get)
  p1_get = p1_entry.get()
  p1yob_get = p1yob_entry.get()
  p1yob_get = int(p1yob_get)
  p1_name_result = Label(root, text=f"{p1_get}'s age in {ty_get}:")
  p1_name_result.grid(row = 4, column = 5)
  p1_age = ty_get - p1yob_get
  p1_age_result = Label(root, text=p1_age)
  p1_age_result.grid(row = 4, column = 6)
  p2_get = p2_entry.get()
  p2yob_get = p2yob_entry.get()
  p2yob_get = int(p2yob_get)
  p2_name_result = Label(root, text=f"{p2_get}'s age in {ty_get}:")
  p2_name_result.grid(row = 5, column = 5)
  p2_age = ty_get - p2yob_get
  p2_age_result = Label(root, text=p2_age)
  p2_age_result.grid(row = 5, column = 6)  
  p3_get = p3_entry.get()
  p3yob_get = p3yob_entry.get()
  p3yob_get = int(p3yob_get)
  p3_name_result = Label(root, text=f"{p3_get}'s age in {ty_get}:")
  p3_name_result.grid(row = 6, column = 5)
  p3_age = ty_get - p3yob_get
  p3_age_result = Label(root, text=p3_age)
  p3_age_result.grid(row = 6, column = 6)  
  p4_get = p4_entry.get()
  p4yob_get = p4yob_entry.get()
  p4yob_get = int(p4yob_get)
  p4_name_result = Label(root, text=f"{p4_get}'s age in {ty_get}:")
  p4_name_result.grid(row = 7, column = 5)
  p4_age = ty_get - p4yob_get
  p4_age_result = Label(root, text=p4_age)
  p4_age_result.grid(row = 7, column = 6) 
  p5_get = p5_entry.get()
  p5yob_get = p5yob_entry.get()
  p5yob_get = int(p5yob_get)
  p5_name_result = Label(root, text=f"{p5_get}'s age in {ty_get}:")
  p5_name_result.grid(row = 8, column = 5)
  p5_age = ty_get - p4yob_get
  p5_age_result = Label(root, text=p5_age)
  p5_age_result.grid(row = 8, column = 6) 
  p6_get = p6_entry.get()
  p6yob_get = p6yob_entry.get()
  p6yob_get = int(p6yob_get)
  p6_name_result = Label(root, text=f"{p6_get}'s age in {ty_get}:")
  p6_name_result.grid(row = 9, column = 5)
  p6_age = ty_get - p6yob_get
  p6_age_result = Label(root, text=p6_age)
  p6_age_result.grid(row = 9, column = 6) 
  p7_get = p7_entry.get()
  p7yob_get = p7yob_entry.get()
  p7yob_get = int(p7yob_get)
  p7_name_result = Label(root, text=f"{p7_get}'s age in {ty_get}:")
  p7_name_result.grid(row = 10, column = 5)
  p7_age = ty_get - p7yob_get
  p7_age_result = Label(root, text=p7_age)
  p7_age_result.grid(row = 10, column = 6)
  p8_get = p8_entry.get()
  p8yob_get = p8yob_entry.get()
  p8yob_get = int(p8yob_get)
  p8_name_result = Label(root, text=f"{p8_get}'s age in {ty_get}:")
  p8_name_result.grid(row = 11, column = 5)
  p8_age = ty_get - p8yob_get
  p8_age_result = Label(root, text=p8_age)
  p8_age_result.grid(row = 11, column = 6)
  p9_get = p9_entry.get()
  p9yob_get = p9yob_entry.get()
  p9yob_get = int(p9yob_get)
  p9_name_result = Label(root, text=f"{p9_get}'s age in {ty_get}:")
  p9_name_result.grid(row = 12, column = 5)
  p9_age = ty_get - p9yob_get
  p9_age_result = Label(root, text=p9_age)
  p9_age_result.grid(row = 12, column = 6)
  p10_get = p10_entry.get()
  p10yob_get = p10yob_entry.get()
  p10yob_get = int(p10yob_get)
  p10_name_result = Label(root, text=f"{p10_get}'s age in {ty_get}:")
  p10_name_result.grid(row = 13, column = 5)
  p10_age = ty_get - p10yob_get
  p10_age_result = Label(root, text=p10_age)
  p10_age_result.grid(row = 13, column = 6)

run_it = Button(root, text="Run it!", command=calc_ages)
run_it.grid(row = 3, column = 4)

root.mainloop()